# Generated by Django 3.1.4 on 2020-12-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('is_valid', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=5)),
                ('last_name', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('joined_date', models.DateTimeField(verbose_name='date joined')),
                ('is_active', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateTimeField(verbose_name='date given')),
                ('modified_date', models.DateTimeField(verbose_name='date modified')),
                ('is_valid', models.CharField(max_length=5)),
                ('AuthId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.authinfo')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isGivenName', to='member.user')),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='givenName', to='member.user')),
            ],
        ),
    ]
