# Generated by Django 3.1.4 on 2020-12-20 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='authinfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='authinfo',
            name='is_valid',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='given_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date given'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='is_valid',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date modified'),
        ),
    ]
