# Generated by Django 3.1.4 on 2020-12-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('drafter', models.CharField(max_length=20)),
                ('status', models.CharField(default='오류', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='related_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=10)),
                ('second', models.CharField(max_length=10)),
                ('third', models.CharField(max_length=10)),
                ('four', models.CharField(max_length=10)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.paper')),
            ],
        ),
    ]
